[build]
  publish = "dist"
  command = "npm ci --legacy-peer-deps && npm run build"

[build.environment]
  NODE_VERSION = "18"

# Proxy API requests to our Python backend
[[redirects]]
  from = "/api/*"
  to = "http://localhost:8000/api/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

# Handle all other routes with the SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
